### ISSUE TITLE
static initialization expressions seem to not be sanitized

### ISSUE THREAD

**Issue by ousado** [waneck/haxe-genc#31] opened 2014-07-12 12:50 UTC
to reproduce compile hxparse, which gives following error:  
UnicodeTestLexer.c:179:1882: error: expected expression before ';' token
  UnicodeTestLexer_root = (c_Closure\* _1,c__hx_anon_27\* _2,c_Closure\* _4,c__hx_anon_27\* _5, ... 

The block is generated using the comma operator, which doesn't allow to define variables.

**Comment by Simn** [comment] 2014-08-14 11:16
The problem is that we run the sanitizer before the generator (obviously), but the generator filters may add additional expressions to `cl_init`.

The order in general is just a big mess. We need the analyzer transformation to simplify the other filters, but we also have to deal with expressions and even entire fields added by these filters. This requires some major cleanup I'm afraid.

**Comment by Simn** [comment] 2014-08-14 11:30
Should be fixed for now.

**Closed as completed by Simn** 2014-08-14 11:30 UTC
